language: php
php:
  - 5.6
  - 7.0
  - 7.1
services:
  - cassandra
before_install:
  - sudo apt-get install g++ make cmake libuv-dev libssl-dev libgmp-dev openssl libpcre3-dev
  - pecl install cassandra
  - phpenv config-rm xdebug.ini
  - phpenv config-add tests/config.ini
install:
  - composer install
script:
  - vendor/bin/phpunit
